## Ucitavanje i Sredjivanje Nizova Podataka

In [83]:
#ucitavanje potrebnih biblioteka
import pandas as pd
import numpy as np

In [84]:
#uvoz podataka
#sezona 23/24
df_23_4 = pd.read_csv("epl-2023.csv")
#sezona 24/25
df_24_5 = pd.read_csv("epl-2024.csv")
#sezona 25/6
df_25_6 = pd.read_csv("epl-2025.csv")

## Ukidanje Duplih Vrijednosti za Nazive Klubova

In [85]:
#za sezonu 25 6
df_25_6["Home Team"] = df_25_6["Home Team"].replace("Nott'm Forest", 'Nottingham Forest')
df_25_6["Away Team"] = df_25_6["Away Team"].replace("Nott'm Forest", 'Nottingham Forest')
#za sezonu 24 5
df_24_5["Home Team"] = df_24_5["Home Team"].replace("Nott'm Forest", 'Nottingham Forest')
df_24_5["Away Team"] = df_24_5["Away Team"].replace("Nott'm Forest", 'Nottingham Forest')

## Određivanje Duzine Trenutnoj Sezoni i Prikaz

In [86]:
#odrediti duzinu sezone - OBAVEZNO!!!
df_25_6 = df_25_6.head(30)
df_25_6.tail()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
25,24,3,30/08/2025 17:30,Elland Road,Leeds,Newcastle,0 - 0
26,22,3,31/08/2025 14:00,American Express Stadium,Brighton,Man City,2 - 1
27,27,3,31/08/2025 14:00,The City Ground,Nottingham Forest,West Ham,0 - 3
28,25,3,31/08/2025 16:30,Anfield,Liverpool,Arsenal,1 - 0
29,21,3,31/08/2025 19:00,Villa Park,Aston Villa,Crystal Palace,0 - 3

In [87]:
#sjedinjavanje ta tri df niza podataka - po osi jedan - odnosno uzduž
df_BL = pd.concat([df_23_4, df_24_5, df_25_6], axis=0)

In [88]:
df_BL["Home Team"].unique()

array(['Burnley', 'Arsenal', 'Bournemouth', 'Brighton', 'Everton',
       'Sheffield Utd', 'Newcastle', 'Brentford', 'Chelsea', 'Man Utd',
       'Nottingham Forest', 'Fulham', 'Liverpool', 'Wolves', 'Spurs',
       'Man City', 'Aston Villa', 'West Ham', 'Crystal Palace', 'Luton',
       'Ipswich', 'Leicester', 'Southampton', 'Sunderland', 'Leeds'],
      dtype=object)

In [89]:
#prikaz sjedinjenog niza podatak 
#tj. sve tri sezone u jednom nizu podataka u obliku df 
df_BL.tail()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
25,24,3,30/08/2025 17:30,Elland Road,Leeds,Newcastle,0 - 0
26,22,3,31/08/2025 14:00,American Express Stadium,Brighton,Man City,2 - 1
27,27,3,31/08/2025 14:00,The City Ground,Nottingham Forest,West Ham,0 - 3
28,25,3,31/08/2025 16:30,Anfield,Liverpool,Arsenal,1 - 0
29,21,3,31/08/2025 19:00,Villa Park,Aston Villa,Crystal Palace,0 - 3

## Predprocesovanje Niza Podataka

In [90]:
#Izbacivanje Nerelevantnih Osobina
df_BL = df_BL.drop(["Match Number","Round Number","Date","Location"],axis=1)
df_BL.shape

(790, 3)

In [91]:
df_BL.rename(columns={"Home Team":"H","Away Team":"A"},inplace=True)

In [92]:
df_BL.to_csv("epl.csv")
df_BL

                    H                  A Result
0             Burnley           Man City  0 - 3
1             Arsenal  Nottingham Forest  2 - 1
2         Bournemouth           West Ham  1 - 1
3            Brighton              Luton  4 - 1
4             Everton             Fulham  0 - 1
..                ...                ...    ...
25              Leeds          Newcastle  0 - 0
26           Brighton           Man City  2 - 1
27  Nottingham Forest           West Ham  0 - 3
28          Liverpool            Arsenal  1 - 0
29        Aston Villa     Crystal Palace  0 - 3

[790 rows x 3 columns]

In [93]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

#One Hot Encoder Timova - Domacin i Gost
onehot_encoder_domacin = OneHotEncoder(handle_unknown="ignore",drop="first")  # Ensure parameters are correct
kodiran_domacin = onehot_encoder_domacin.fit_transform(df_BL[["H"]]).toarray()
df_domacin = pd.DataFrame(kodiran_domacin,columns=onehot_encoder_domacin.get_feature_names_out(["H"]))

In [94]:
df_domacin.columns

Index(['H_Aston Villa', 'H_Bournemouth', 'H_Brentford', 'H_Brighton',
       'H_Burnley', 'H_Chelsea', 'H_Crystal Palace', 'H_Everton', 'H_Fulham',
       'H_Ipswich', 'H_Leeds', 'H_Leicester', 'H_Liverpool', 'H_Luton',
       'H_Man City', 'H_Man Utd', 'H_Newcastle', 'H_Nottingham Forest',
       'H_Sheffield Utd', 'H_Southampton', 'H_Spurs', 'H_Sunderland',
       'H_West Ham', 'H_Wolves'],
      dtype='object')

In [95]:
#One Hot Encoder Timova - Gosti
onehot_encoder_gost = OneHotEncoder(handle_unknown="ignore",drop="first")  # Ensure parameters are correct
kodiran_gost = onehot_encoder_gost.fit_transform(df_BL[["A"]]).toarray()
df_gost = pd.DataFrame(kodiran_gost,columns=onehot_encoder_gost.get_feature_names_out(["A"]))

In [96]:
#Sjedinjavanje tih osobina domacin i gost
df_jedan = pd.concat([df_domacin,df_gost],axis=1)
df_jedan

,H_Aston Villa,H_Bournemouth,H_Brentford,H_Brighton,H_Burnley,H_Chelsea,H_Crystal Palace,H_Everton,H_Fulham,H_Ipswich,...,A_Man City,A_Man Utd,A_Newcastle,A_Nottingham Forest,A_Sheffield Utd,A_Southampton,A_Spurs,A_Sunderland,A_West Ham,A_Wolves
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
786,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
788,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
789,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Transformisanje Rezultata u Varijablu - Y Varijable

#### Stvaranje Vrijednosti za Dvije Kolone iz Jedne Osobine/Kolone Rezultat

In [97]:
rez_dom = df_BL["Result"].str.slice(0,1)

In [98]:
rez_dom.head()

0    0
1    2
2    1
3    4
4    0
Name: Result, dtype: object

In [99]:
rez_gost = df_BL["Result"].str.slice(4,5)

In [100]:
rez_gost.head()

0    3
1    1
2    1
3    1
4    1
Name: Result, dtype: object

In [101]:
df_rezultatski = pd.concat([df_BL,rez_dom,rez_gost],axis=1)

In [102]:
#promjena naziva kolonama - spajanjem smo dobili kolone istih naziva
df_rezultatski.columns = ["H","A","Result","Rez1","Rez2"]
df_rezultatski.tail()

                    H               A Result Rez1 Rez2
25              Leeds       Newcastle  0 - 0    0    0
26           Brighton        Man City  2 - 1    2    1
27  Nottingham Forest        West Ham  0 - 3    0    3
28          Liverpool         Arsenal  1 - 0    1    0
29        Aston Villa  Crystal Palace  0 - 3    0    3

In [103]:
#spremanje df_epl varijable za obradu osobine Result u excelu
df_rezultatski.to_csv("uredjivanje_skora_vani.csv")

## Uocavanje Indeksa Sezona - za Kasnije Floatiranje

In [104]:
#df_rezultatski[0:380] #sezona 23/4 od 0:380
#df_rezultatski[380:759] #sezona 24/5 od 380:759
#df_rezultatski[760:] #sezona25/6 od 760:

## Stvaranje Kolone Skor sa Vrijednostima - Ovdje

In [105]:
# Define a function to perform the conditional logic
def calculate_value(row):
    if row['Rez1'] > row['Rez2']:
        return 1
    elif row['Rez1'] < row['Rez2']:
        return -1
    else:  # row['Column1'] == row['Column2']
        return 0

In [106]:
# Apply the function to each row in the DataFrame and assign the result to a new column
df_rezultatski['Skor'] = df_rezultatski.apply(calculate_value, axis=1)
skor = df_rezultatski.drop(['H', 'A', 'Result', 'Rez1',"Rez2"],axis=1)

### Floatiranje Vrijednosti Kolone Skor - po Sezonama

Kopiraj - Izmjeni celiju ispod sa gore izracunatim vrijednostima indeksa sezona

#df_rezultatski[0:380] #sezona 23/4 od 0:380
#df_rezultatski[380:759] #sezona 24/5 od 380:759
#df_rezultatski[760:] #sezona25/6 od 760:

In [107]:
#sezona 23/4
skor23_4 = skor[0:380]
skor24_5 = skor[380:760]
skor25_6 = skor[760:]

In [108]:
#skor.head(3)
skor23_4["Skor"] = skor23_4["Skor"] * 0.71

C:\Users\amirb\AppData\Local\Temp\ipykernel_6176\3544292283.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skor23_4["Skor"] = skor23_4["Skor"] * 0.71

In [109]:
skor24_5["Skor"] = skor24_5["Skor"] * 0.85

C:\Users\amirb\AppData\Local\Temp\ipykernel_6176\3136881136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skor24_5["Skor"] = skor24_5["Skor"] * 0.85

## Konačna kolona Skor - Sjedinjavanje Vrijednosti Sezona

In [110]:
skor = pd.concat([skor23_4, skor24_5, skor25_6], axis=0, ignore_index=True)

Provjera se vrši manuelno, gledanjem repa,glave i sredine ovog df-a

In [111]:
df_rezultatski = df_rezultatski.reset_index(drop=True)
skor = skor.reset_index(drop=True)

In [112]:
#provjera rezultata
finalna_provjera = pd.concat([df_rezultatski,skor],axis=1,ignore_index=True)
finalna_provjera = finalna_provjera.drop([3,4,5],axis=1)
finalna_provjera.columns = ["H","A","Rezultat","Skor"]

In [113]:
finalna_provjera[-5:-1]

                     H          A Rezultat  Skor
785              Leeds  Newcastle    0 - 0   0.0
786           Brighton   Man City    2 - 1   1.0
787  Nottingham Forest   West Ham    0 - 3  -1.0
788          Liverpool    Arsenal    1 - 0   1.0

# Konačni df - Podaci su Sređeni

In [114]:
skor = skor.reset_index(drop=True)
df_jedan = df_jedan.reset_index(drop=True)

In [115]:
df_BL = pd.concat([df_jedan,skor],axis=1)

In [116]:
df_BL.head(5)

,H_Aston Villa,H_Bournemouth,H_Brentford,H_Brighton,H_Burnley,H_Chelsea,H_Crystal Palace,H_Everton,H_Fulham,H_Ipswich,...,A_Man Utd,A_Newcastle,A_Nottingham Forest,A_Sheffield Utd,A_Southampton,A_Spurs,A_Sunderland,A_West Ham,A_Wolves,Skor
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.71
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.71
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.71
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.71

In [117]:
#spremanje kodiranog niza podataka
df_BL.to_csv("kodirani_epl.csv")

## Razdvajanje Niza Podataka na Osobine za Predvidjanje i Ciljanu Osobinu

In [118]:
# X predvidjacke, y varijabla jeste Skor Osobina
X = df_BL.drop(["Skor"],axis=1)
y = df_BL["Skor"]

In [119]:
#razdvajanje podataka u treniranju i testirajuce nizove
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)
X_train.head()

,H_Aston Villa,H_Bournemouth,H_Brentford,H_Brighton,H_Burnley,H_Chelsea,H_Crystal Palace,H_Everton,H_Fulham,H_Ipswich,...,A_Man City,A_Man Utd,A_Newcastle,A_Nottingham Forest,A_Sheffield Utd,A_Southampton,A_Spurs,A_Sunderland,A_West Ham,A_Wolves
342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
740,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
192,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [120]:
#skaliranje ovih osobina
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.24090603, -0.23429926, -0.22410169, ..., -0.03752933,
        -0.23094011, -0.23429926],
       [-0.24090603, -0.23429926, -0.22410169, ..., -0.03752933,
        -0.23094011, -0.23429926],
       [-0.24090603, -0.23429926, -0.22410169, ..., -0.03752933,
        -0.23094011, -0.23429926],
       ...,
       [-0.24090603, -0.23429926, -0.22410169, ..., -0.03752933,
        -0.23094011, -0.23429926],
       [-0.24090603, -0.23429926, -0.22410169, ..., -0.03752933,
        -0.23094011, -0.23429926],
       [-0.24090603, -0.23429926, -0.22410169, ..., -0.03752933,
        -0.23094011, -0.23429926]])

In [121]:
#Spremanje tog Kodera - za Kasniju Upotrebu

with open("onehot_encoder_domacin.pkl","wb") as file:
    pickle.dump(onehot_encoder_domacin,file)
    
with open("onehot_encoder_gost.pkl","wb") as file:
    pickle.dump(onehot_encoder_gost,file)
    
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

## Stvaranje Modela i Dobijanje Predikcije

In [74]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
#sledeca biblioteka se odnosi na stvaranje neurona iz kutije layers i alatom dense
from tensorflow.keras.layers import Dense

In [75]:
#konstrukcija modela
model=Sequential([
    Dense(16,activation="relu",input_shape=(X_train.shape[1],)), #HL1 connected to I/p - Skriveni Sloj 1 povezan sa I/p
    Dense(1)
])

In [76]:
#Oblikovanje Modela 
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])
model.summary()

# Keras dokumentacija pojasnjava sta se dogodi sa razlicitim odabirom "loss" i drugih parametara

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                784

 dense_1 (Dense)             (None, 1)                 17

=================================================================
Total params: 801
Trainable params: 801
Non-trainable params: 0
_________________________________________________________________

In [77]:
import datetime
#uspostavljanje Tensorboard-a, zapocinjanje treniranja
#TensorBoard sluzi samo za vizualizaciju svih logovanja koje izvrsim kod treniranja nekog modela
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

#log_dir varijabla koja osigurava da ostane zabinjezen trag svakog treniranja modela
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

#Uspostavljanje Early Stopping - sluzi za zaustavljanje treniranja ako se vrijednost gubitaka ne smanjuje
#bitni parametri su uneseni koji sluze poboljsanju funkcije ranog zaustavljanja treniranja modela...
early_stopping_callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [78]:
#TRENIRANJE MODELA / Tovarenje Modela
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=50,
    callbacks= [tensorflow_callback,early_stopping_callback]
)

Epoch 1/50
23/23 [==============================] - 7s 82ms/step - loss: 1.0309 - mae: 1.0309 - val_loss: 0.9210 - val_mae: 0.9210
Epoch 2/50
23/23 [==============================] - 0s 19ms/step - loss: 0.8717 - mae: 0.8717 - val_loss: 0.8272 - val_mae: 0.8272
Epoch 3/50
23/23 [==============================] - 0s 18ms/step - loss: 0.7675 - mae: 0.7675 - val_loss: 0.7525 - val_mae: 0.7525
Epoch 4/50
23/23 [==============================] - 0s 15ms/step - loss: 0.6974 - mae: 0.6974 - val_loss: 0.7047 - val_mae: 0.7047
Epoch 5/50
23/23 [==============================] - 0s 14ms/step - loss: 0.6471 - mae: 0.6471 - val_loss: 0.6776 - val_mae: 0.6776
Epoch 6/50
23/23 [==============================] - 0s 14ms/step - loss: 0.6123 - mae: 0.6123 - val_loss: 0.6571 - val_mae: 0.6571
Epoch 7/50
23/23 [==============================] - 0s 17ms/step - loss: 0.5869 - mae: 0.5869 - val_loss: 0.6481 - val_mae: 0.6481
Epoch 8/50
23/23 [==============================] - 0s 13ms/step - loss: 0.5685 - mae: 0.5685 - val_loss: 0.6402 - val_mae: 0.6402
Epoch 9/50
23/23 [==============================] - 0s 13ms/step - loss: 0.5538 - mae: 0.5538 - val_loss: 0.6324 - val_mae: 0.6324
Epoch 10/50
23/23 [==============================] - 0s 14ms/step - loss: 0.5394 - mae: 0.5394 - val_loss: 0.6269 - val_mae: 0.6269
Epoch 11/50
23/23 [==============================] - 0s 15ms/step - loss: 0.5289 - mae: 0.5289 - val_loss: 0.6233 - val_mae: 0.6233
Epoch 12/50
23/23 [==============================] - 0s 14ms/step - loss: 0.5193 - mae: 0.5193 - val_loss: 0.6117 - val_mae: 0.6117
Epoch 13/50
23/23 [==============================] - 0s 14ms/step - loss: 0.5111 - mae: 0.5111 - val_loss: 0.6062 - val_mae: 0.6062
Epoch 14/50
23/23 [==============================] - 0s 14ms/step - loss: 0.5032 - mae: 0.5032 - val_loss: 0.6060 - val_mae: 0.6060
Epoch 15/50
23/23 [==============================] - 0s 14ms/step - loss: 0.4989 - mae: 0.4989 - val_loss: 0.5988 - val_mae: 0.5988
Epoch 16/50
23/23 [==============================] - 0s 16ms/step - loss: 0.4920 - mae: 0.4920 - val_loss: 0.5989 - val_mae: 0.5989
Epoch 17/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4859 - mae: 0.4859 - val_loss: 0.6001 - val_mae: 0.6001
Epoch 18/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4818 - mae: 0.4818 - val_loss: 0.5984 - val_mae: 0.5984
Epoch 19/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4773 - mae: 0.4773 - val_loss: 0.5915 - val_mae: 0.5915
Epoch 20/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4719 - mae: 0.4719 - val_loss: 0.5877 - val_mae: 0.5877
Epoch 21/50
23/23 [==============================] - 0s 16ms/step - loss: 0.4677 - mae: 0.4677 - val_loss: 0.5862 - val_mae: 0.5862
Epoch 22/50
23/23 [==============================] - 0s 14ms/step - loss: 0.4624 - mae: 0.4624 - val_loss: 0.5857 - val_mae: 0.5857
Epoch 23/50
23/23 [==============================] - 0s 19ms/step - loss: 0.4580 - mae: 0.4580 - val_loss: 0.5871 - val_mae: 0.5871
Epoch 24/50
23/23 [==============================] - 0s 16ms/step - loss: 0.4529 - mae: 0.4529 - val_loss: 0.5737 - val_mae: 0.5737
Epoch 25/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4503 - mae: 0.4503 - val_loss: 0.5758 - val_mae: 0.5758
Epoch 26/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4486 - mae: 0.4486 - val_loss: 0.5802 - val_mae: 0.5802
Epoch 27/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4429 - mae: 0.4429 - val_loss: 0.5779 - val_mae: 0.5779
Epoch 28/50
23/23 [==============================] - 0s 18ms/step - loss: 0.4392 - mae: 0.4392 - val_loss: 0.5682 - val_mae: 0.5682
Epoch 29/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4364 - mae: 0.4364 - val_loss: 0.5709 - val_mae: 0.5709
Epoch 30/50
23/23 [==============================] - 0s 16ms/step - loss: 0.4330 - mae: 0.4330 - val_loss: 0.5706 - val_mae: 0.5706
Epoch 31/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4312 - mae: 0.4312 - val_loss: 0.5707 - val_mae: 0.5707
Epoch 32/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4265 - mae: 0.4265 - val_loss: 0.5638 - val_mae: 0.5638
Epoch 33/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4239 - mae: 0.4239 - val_loss: 0.5687 - val_mae: 0.5687
Epoch 34/50
23/23 [==============================] - 0s 13ms/step - loss: 0.4198 - mae: 0.4198 - val_loss: 0.5675 - val_mae: 0.5675
Epoch 35/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4189 - mae: 0.4189 - val_loss: 0.5666 - val_mae: 0.5666
Epoch 36/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4159 - mae: 0.4159 - val_loss: 0.5670 - val_mae: 0.5670
Epoch 37/50
23/23 [==============================] - 0s 17ms/step - loss: 0.4136 - mae: 0.4136 - val_loss: 0.5676 - val_mae: 0.5676
Epoch 38/50
23/23 [==============================] - 0s 15ms/step - loss: 0.4099 - mae: 0.4099 - val_loss: 0.5691 - val_mae: 0.5691
Epoch 39/50
23/23 [==============================] - 0s 16ms/step - loss: 0.4094 - mae: 0.4094 - val_loss: 0.5671 - val_mae: 0.5671
Epoch 40/50
23/23 [==============================] - 0s 18ms/step - loss: 0.4056 - mae: 0.4056 - val_loss: 0.5672 - val_mae: 0.5672
Epoch 41/50
23/23 [==============================] - 0s 20ms/step - loss: 0.4038 - mae: 0.4038 - val_loss: 0.5732 - val_mae: 0.5732
Epoch 42/50
23/23 [==============================] - 0s 13ms/step - loss: 0.4030 - mae: 0.4030 - val_loss: 0.5699 - val_mae: 0.5699

In [79]:
#Procjena Rada Modela preko test podataka
test_loss, test_mae = model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 7ms/step - loss: 0.5638 - mae: 0.5638

In [80]:
#spremanje modela
model.save("epl_float_model.h5")

In [81]:
#moze biti da skaliranje je neophodno, onda je potrebno i obnoviti test parametara modela, te iznova
#-trenirati model i na kraju ga ponovo spremiti.